### ISSUE TITLE
Sign-up and Login always share the same page

### ISSUE THREAD

**Issue by caymanmckee** [CarterMcClellan/HPR#18]
Whenever it asks for the user to login again, it pops up with both registration and the login. It would feel more polished if they were separate pages, or only have one set of fields and two buttons. Whenever a user enters that page, most browser autocomplete password systems will complete both sets of fields which can lead to user mistaking the buttons.

Severity: Low

**Comment by CarterMcClellan** [comment]
this was a design decision, we actually originally had a login and register as separate pages
